name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  SHOWWCASE_API_KEY:
    description: "Showwcase api key"
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
