name: Post security news 

on:
  workflow_dispatch:
  schedule:
  - cron: "0 23 * * *" # triggers everyday 23:00 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install node dependencies
      run: npm install

    - name: Run Security Feed Action
      uses: ./ # Uses an action in the root directory
      with:
        SHOWWCASE_API_KEY: ${{ secrets.SHOWWCASE_API_KEY }}
